package user

import (
	"net/http"
	"encoding/json"
)

// User represents a user in the system
// GetUser handles the retrieval of a user by ID
func GetUsers(w http.ResponseWriter, r *http.Request) {
}


// CreateUser handles the creation of a new user
func CreateUser(w http.ResponseWriter, r *http.Request) {
	var user User
	err := json.NewDecoder(r.Body).Decode(&user)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	user.ID = 2 // This should be generated by your database

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(user)
}